on:
  workflow_dispatch
jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          cd /tmp
          git clone https://github.com/SrsSec/SrsPass-pwa.git --depth 1
          cd SrsPass-pwa
          npm ci
          npm run build
          git rev-parse --short HEAD | tr =d '\n' > dist/GIT_HASH
      - uses: actions/checkout@v1
      - name: commit & stage build
        env:
          BRANCH: stage
        run: |
          git config user.email "github+CHAPPiE@srssec.com"
          git config user.name "SrsSec-CHAPPiE"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          git checkout --orphan "$BRANCH"
          git reset --hard
          cp -a /tmp/SrsPass-pwa/dist/. .
          echo internal-use-only-staging.srspass.com > CNAME
          git add .
          git commit -m "stage: $(cat GIT_HASH)"
          git push origin -f "$BRANCH"
