on:
  workflow_dispatch
jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: ls-test
        run: |
          ls
          pwd
      - name: build
        run: |
          git clone https://github.com/SrsSec/SrsPass-pwa.git
          cd SrsPass-pwa
          npm ci
          npm run build
          ls
      - name: commit & stage build
        run: |
          ls
          pwd
          cd
          ls
          pwd
